resources:
  containers:
  - container: build_container
    image: msftxlang.azurecr.io/xlang-ubuntu-build
    endpoint: msftxlang_acr

pool:
  vmImage: 'ubuntu-16.04'

container: build_container

steps:
- task: CMake@1
  displayName: configure
  inputs:
    cmakeArgs: '../src -GNinja'
- task: CMake@1
  displayName: build
  inputs:
    cmakeArgs: '--build . -- -v'
